services:
  - type: web
    name: flask-face-api-1
    env: python
    plan: free
    region: oregon
    buildCommand: |
      echo "ðŸ“¦ Preparing build..."
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
