services:
  - type: web
    name: flask-face-api
    env: python
    plan: free
    preBuildCommand: echo "Preparing build..."
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
